### ISSUE TITLE
AIMA 4th Edition Algorithm File

### ISSUE THREAD

**Issue by berviantoleo** [aimacode/aima-pseudocode#35]
Hello. I new here. I see there is AIMA 3th Edition Algorithm File. When I see in `aima-java`, in there have issue wants to add implementation of 4th edition Algorithm. Are 4th edition released? If yes, how about added 4th edition into this repo?

**Comment by ShobhitLamba** [comment]
Hello there. Welcome to aimacode. 
The 4th edition is still a work in progress, and everything has not been finalized as of yet. Additions to all the repos are made as soon as possible. Any changes or additions made are also reflected in the source code. You can go through the different implementations as well as the pseudocode, and pick up anything you would like to work on. Just check with others so that you don't end up working on the same thing someone else is already working on.
