### ISSUE TITLE
 Asymmetric reproduce function in Genetic algorithm

### ISSUE THREAD

**Issue by Chipe1** [aimacode/aima-pseudocode#48]
I know this is pedantic, but shouldn't `c` range from `0` to `n ` instead of `1` to `n`. Else we would have more of `x` on average compared to `y`.
In our application `x` and `y` are picked randomly from the same distribution so it won't make a difference, but still it would be nice to have it unaffected by order of arguments.
[Genetic algorithm](https://github.com/aimacode/aima-pseudocode/blob/master/md/Genetic-Algorithm.md)

**Comment by MrDupin** [comment]
One solution would be to pick `c` in the range [0, n]. That way there is a chance that the offspring will be `x` or `y`. I don't know if this is desirable, but it is fairer to the parents.

**Comment by Chipe1** [comment]
I'm not sure if we should have `[0, n]` or `[1, n-1]`. This would affect the probability of cloning. So a population with a very rare DNA/string would have better chance of surviving if `n` is smaller than population size.

**Comment by kaivalyar** [comment]
When I read the pseudocode, my interpretation was based on an indexing of strings from 1 to len, where len was the index of the last valid character. In this case, the pseudocode as it currently is would not have any such bias (I think).

Here is the pseudocode:
n ← LENGTH(x); c ← random number from 1 to n
 return APPEND(SUBSTRING(x, 1, c),SUBSTRING(y, c+1, n))

Example:
x <- "abcde"
y <- "vwxyz"

each string has indices 1, 2, 3, 4, 5
n <- length - (therefore n = 5)
picking a random number c between 1 to 5 (both inclusive) doesn't introduce any biases, eg let c <- 2
therefore SUBSTRING(x, 1, c) yields "ab" (since c = 2, we select indices 1 and 2)
and SUBSTRING(y, c+1, n) yields "xyz" - (since c+1 = 3, we select indices 3, 4, and 5)

giving an unbiased answer of "abxyz"

So maybe we can change the python/java implementations according to the indexing conventions of the languages, but the pseudocode may not require alteration, but rather an explicit explanation of its indexing conventions.

**Comment by kaivalyar** [comment]
Update: Section B.2 in the appendix (page 1062) clearly mentions this convention already. I think the pseudocode is correct in this case.

**Comment by Chipe1** [comment]
@kaivalyar I think you didn't get what I mean by biased. The output of `reproduce(s1, s2)` and `reproduce(s2, s1)` give outputs form different distributions. `reproduce(x, y)` has `1/n` chance of returning `x` but zero chance of returning `y`. This is because `c` can take a value of `n` which would make `SUBSTRING(y, c+1 = n+1, n)` an empty string. Now as `c` can't be `0`, we will always have the first character from `x` which makes the function biased as it always chooses a character from `x` but not `y`.
There is also a choice we can make here by letting `c` range in `[0, n]` or range in `[1, n-1]`. As explained in my above comment, these two mat drastically affect the evolution of uncommon sequences. The current range of `[1, n]` works perfectly fine as `x` and `y` are picked from the same distribution but I feel it would be better if `reproduce(x, y)` and `reproduce(y, x)` return from the same distribution.

**Comment by MrDupin** [comment]
@Chipe1: The current range is [1, n-1]. `randrange` (the function we are using) doesn't include the *stop* value. So we can get no duplication of parents. The offspring will at all cases be part `x` and part `y`.

**Comment by Chipe1** [comment]
@MrDupin `randrange(1, n)` is used in the python implementation. The pseudocode still picks from `1` to `n` inclusive. The js imlpementation picks from `0` to `n-1` and starts `y` from index `c` which makes it biased towards `y`.

**Comment by MrDupin** [comment]
@Chipe1: `randrange(1, n)` is not inclusive. The [official documentation](https://docs.python.org/3/library/random.html) is not clear, even though it says the function follows the positional pattern of `range` (which is not inclusive).

Also, online unfortunately there are conflicting views (even on the same articles). For example, the [TutorialsPoint article](https://www.tutorialspoint.com/python3/number_randrange.htm). First it says it's inclusive, but on the example says it isn't.

There are though views of its exclusiveness, like [this](https://www.codecademy.com/en/forum_questions/521bcf2b548c359b28000367).

The best thing to do is run an example, to see for yourself:

```
from random import randrange

ones = 0
twos = 0
threes = 0
fours = 0

other = 0

for i in range(10000):
    r = randrange(1, 4)
    if(r == 1):
        ones += 1
    elif(r == 2):
        twos += 1
    elif(r == 3):
        threes += 1
    elif(r == 4):
        fours += 1
    else:
        other += 1

print("Ones:",ones)
print("Twos:",twos)
print("Threes:",threes)
print("Fours:",fours)
print("Other:",other)
```

In the above I use `randrange(1, 4)`, and I show that the random values are distributed (pretty much evenly) in [1, 3], with 4 having no examples. You can run the above as many times as you want and no value above 3 will appear, because it is not inclusive.

**Comment by Chipe1** [comment]
@MrDupin I meant that `randrange` is used in the python implementation and not in the pseudocode. That would make the python implementation fair to both `x` and `y` but the pseudocode and js implementation are still all different from each other.

**Comment by MrDupin** [comment]
Ah, I thought in your previous comment you wrote `randrange` instead of `reproduce`. My bad, I get it now. In the pseudocode it reads "from 1 to n", where it should be "from 1 to n-1" for the reproduction to be fair.

**Comment by norvig** [comment]
I agree weith the conclusion here -- the pseudocode should change.

**Comment by norvig** [comment]
Also, I would do the example code for randrange as

     Counter(randrange(1, 4) for _ in range(100000))

**Comment by MrDupin** [comment]
Thanks for the tip @norvig. Python never ceases to amaze me.
